apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtest-deployment
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: devtest
  template:
    metadata:
      labels:
        app: devtest
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
